[network]
listen_address = "/ip4/0.0.0.0/tcp/6884"
dial_peers = []
enable_mdns = true
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 50
max_established_outgoing = 50
max_established_per_peer = 1

[store]
path = "./store.db"

[ckpool]
host = "localhost"
port = 8881

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoin]
network = "signet"
# RPC credentials are loaded from env vars
url = "http://localhost:38332"
username = "p2pool"
password = "p2pool"
