[network]
listen_address = "/ip4/0.0.0.0/tcp/6884"
dial_peers = []
enable_mdns = true
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 50
max_established_outgoing = 50
max_established_per_peer = 1
max_workbase_per_second = 10
max_userworkbase_per_second = 10
max_miningshare_per_second = 100
max_inventory_per_second = 100
max_transaction_per_second = 100
rate_limit_window_secs = 1
# (max_miningshare_per_second + max_workbase_per_second + max_userworkbase_per_second) * 2
max_concurrent_tasks = 240

[store]
path = "./store.db"

[ckpool]
host = "localhost"
port = 8881

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoin]
network = "signet"
# RPC credentials are loaded from env vars
url = "http://localhost:38332"
username = "p2pool"
password = "p2pool"

[logging]
# For system run services you can specify a file path
# file = "/var/log/p2pool/p2pool.log"
# For container or local run it is recommended to use console output
console = false
level = "debug"
