[network]
listen_address = "/ip4/127.0.0.1/tcp/6884"
dial_peers = []
max_pending_incoming = 10
max_pending_outgoing = 10
max_established_incoming = 50
max_established_outgoing = 50
max_established_per_peer = 1
max_workbase_per_second = 10
max_userworkbase_per_second = 10
max_miningshare_per_second = 100
max_inventory_per_second = 100
max_transaction_per_second = 100
rate_limit_window_secs = 1

[store]
path = "./store.db"

[ckpool]
host = "localhost"
port = 8881

[stratum]
host = "localhost"
port = 3333
start_difficulty = 1
minimum_difficulty = 1
solo_address = "tb1qyazxde6558qj6z3d9np5e6msmrspwpf6k0qggk"

[miner]
pubkey = "020202020202020202020202020202020202020202020202020202020202020202"

[bitcoin]
# The network can be "main", "testnet4" or "signet"
network = "signet"

[bitcoinrpc]
# RPC credentials are loaded from env vars
url = "http://localhost:38332"
username = "p2pool"
password = "p2pool"

[logging]
# For system run services you can specify a file path
# file = "/var/log/p2pool/p2pool.log"
# For container or local run it is recommended to use console output
console = false
level = "debug"

[[tests]]
name = "integration"
path = "tests.main"
