image:https://github.com/p2poolv2/p2poolv2/actions/workflows/rust.yml/badge.svg[Rust CI, link=https://github.com/p2poolv2/p2poolv2/actions/workflows/rust.yml]
image:https://codecov.io/gh/p2poolv2/p2poolv2/graph/badge.svg?token=Xeu4GFdASS[Codecov, link=https://codecov.io/gh/p2poolv2/p2poolv2]

We chat on https://matrix.to/#/#p2poolv2:matrix.org[Matrix].

We use https://github.com/p2poolv2/p2poolv2/wiki[github wiki] for most design documents and tools for developers.

We are tracking progress using our https://github.com/orgs/p2poolv2/projects/1[Github project: Reboot P2Pool].

See detailed https://github.com/p2poolv2/p2poolv2/wiki/Developer-Setup-Notes[Developer Setup Notes] on the wiki.

== P2Pool V2

A reboot of the original P2Pool decentralized mining pool.

1. Share chain with uncles - all your work is accounted for.
2. Pay large miners in coinbase - non custodial solution for top N miners.
3. Support transactions - pay all miners with atomic swaps by market makers.
4. Market makers buy shares from smaller miners - earning virgin coins.

== Development

=== Git Hooks

To ensure code quality and consistency, we use git hooks. To set them up, run:

[,shell]
----
just setup-dev
----

== Run with Docker

All docker commands are run from the `docker` directory.

Start your local p2pool node:

[,shell]
----
cd docker
docker compose up -d
----

Shutdown your local p2pool node:

[,shell]
----
docker compose down
----

=== Run individual docker containers

During development, you may want to run individual containers.

Remember, all docker commands are run from the docker directory.

=== Start bitcoind signet

`docker compose up bitcoind`

=== Start p2poolv2

[,shell]
----
docker compose up p2pool
----

=== Start cpuminer to start producing shares

[,shell]
----
docker compose up cpuminer
----

== Developer Setup

To ease development of p2pool's rust node, there is a devcontainer setup in place. You can use it
for IDEs supporting devcontainers and github codespaces.

=== MSRV and Edition

MSRV 1.88 with 2024 edition is required to build p2poolv2.

== Masochistic Setup

Follow the guidelines below to setup your local p2pool node. Note, these are not setup instructions,
and we do not support masochistic setups. You are on your own.

. Setup bitcoind
.. Use `docker/bitcoin-signet.conf` as your bitcoin.conf
. Setup p2poolv2
.. Use `src/config.toml` as starting point for your own `config.toml`
. Point your miners to `localhost:3333`
