image:https://github.com/p2poolv2/p2poolv2/actions/workflows/rust.yml/badge.svg[Rust CI, link=https://github.com/p2poolv2/p2poolv2/actions/workflows/rust.yml]
image:https://codecov.io/gh/p2poolv2/p2poolv2/graph/badge.svg?token=Xeu4GFdASS[Codecov, link=https://codecov.io/gh/p2poolv2/p2poolv2]

== P2Poolv2

****
**Mission:** ##Replace pool operators with miners##
****

P2Poolv2 is a peer-to-peer Bitcoin mining pool where miners coordinate
directly and verify their rewards without centralized operators.

1. Share chain with uncles - all your work is accounted for.
2. Pay large miners in coinbase - non custodial solution for top N miners.
3. Support transactions - pay all miners with atomic swaps by market makers.
4. Market makers buy shares from smaller miners - earning virgin coins.

--
We chat on https://matrix.to/#/#p2poolv2:matrix.org[Matrix].

We use https://github.com/p2poolv2/p2poolv2/wiki[github wiki] for most design documents and tools for developers.

We are tracking progress using our https://github.com/orgs/p2poolv2/projects/1[Github project: Reboot P2Pool].

See detailed https://github.com/p2poolv2/p2poolv2/wiki/Developer-Setup-Notes[Developer Setup Notes] on the wiki.
--

== API and CLI READMEs

Both the API and CLI crates provide detailed documentation on how to
use them in their individual crates.

link:p2poolv2_api/README.md[API Documentation]

link:p2poolv2_cli/README.md[CLI Documentation]

=== MSRV and Edition

MSRV 1.88 with 2024 edition is required to build p2poolv2.

== Build

. Install rust from link:https://rustup.rs/[rustup]
. Install link:https://github.com/casey/just?tab=readme-ov-file#installation[Install just]
. Build P2Poolv2
.. Get latest source `git clone git@github.com:p2poolv2/p2poolv2.git`
.. Build `just build-release`

== Run

Follow the guidelines below to setup your local p2pool node.

. bitcoind
.. For signet we provide a `docker/bitcoin-signet.conf` that you can use as your bitcoin.conf
. p2poolv2
.. copy Use `config.sample.toml` to `config.toml` and edit as required
.. at the very least you need to provide the bitcoind rpc details under the `[bitcoinrpc]` section
.. Run P2Poolv2 `just run config.toml`
. Point your miners to `localhost:3333`


== Systemd Service

To setup as a systemd service, use the systemd service file link:./p2poolv2.service[p2poolv2.service]
