# Node Config


[node]
# The path where the underlying LDK and BDK persist their data.
storage_dir_path = "data/ldk_node"
#storage_dir_path = "data/test"

# Network [Bitcoin, Testnet, Testnet4, Signet, Regtest]
network = "Signet"

# The addresses on which the node will listen for incoming connections.
# has to be in format of TcpIpV4, TcpIpV6, OnionV2, OnionV3 and multiple socket address can be given as a list.
# only allow opening and accepting public channels if the node_alias and the listening_addresses are set.
listening_addresses = "127.0.0.1:9735"
#listening_addresses = "127.0.0.1:9734"

# The node alias that will be used when broadcasting announcements to the gossip network.
# The provided alias must be a valid UTF-8 string and no longer than 32 bytes in total.
node_alias = "p2pool_mm_node"

# bitcoin esplora_url
esplora_url = "https://mutinynet.com/api/"

# set gossip source rgs
rgs_server_url = "https://mutinynet.ltbl.io/snapshot"

#HTLC config 
[htlc]

# db path
db_path = "data/htlc_db"

# private key
private_key = "c929c768be0902d5bb7ae6e38bdc6b3b24cefbe93650da91975756a09e408460"

# RPC URL for HTLC configuration
rpc_url = "https://mutinynet.com/api/"

#bitcoin_netowrk 
bitcoin_network = "signet"

confirmation_threshold = 3
min_buffer_block_for_refund = 2

