[package]
name = "p2poolv2_address"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "P2Poolv2 share chain address type: bech32m encoded taproot output keys"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bitcoin = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
serde_json = { workspace = true }
