// Copyright (C) 2024-2026 P2Poolv2 Developers (see AUTHORS)
//
// This file is part of P2Poolv2
//
// P2Poolv2 is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// P2Poolv2 is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// P2Poolv2. If not, see <https://www.gnu.org/licenses/>.

use crate::accounting::OutputPair;
use crate::shares::witness_commitment::WitnessCommitment;
use crate::stratum::session::{EXTRANONCE1_SIZE, EXTRANONCE2_SIZE};
use crate::stratum::work::error::WorkError;
use crate::utils::time_provider::TimeProvider;
use bitcoin::absolute::LockTime;
use bitcoin::blockdata::script::Builder;
use bitcoin::consensus::{deserialize, serialize};
use bitcoin::hashes::{self, Hash, sha256d};
use bitcoin::network::Network;
use bitcoin::script::{Instruction, PushBytesBuf};
use bitcoin::transaction::{Sequence, Transaction, TxIn, TxOut, Version};
use bitcoin::{Address, Amount, opcodes};
use hashes::sha256;
use hex::FromHex;

pub(crate) const EXTRANONCE_SEPARATOR: [u8; EXTRANONCE1_SIZE + EXTRANONCE2_SIZE] =
    [1u8; EXTRANONCE1_SIZE + EXTRANONCE2_SIZE];

/// Length of the sequence bytes in coinbase
const SEQUENCE_LENGTH: usize = 4;

/// Length of the lock time bytes in coinbase
const LOCKTIME_LENGTH: usize = 4;

/// Sequence for coinbase
const BIP54_COINBASE_SEQUENCE: Sequence = Sequence(0xffff_fffe);

/// Parse Address from a string provided by the miner.
///
/// Delegates to `p2poolv2_config::parse_address` and converts the error.
#[allow(dead_code)]
pub fn parse_address(address: &str, network: Network) -> Result<Address, WorkError> {
    p2poolv2_config::parse_address(address, network).map_err(WorkError::from)
}

/// Get timestamp from provider, in seconds and nanoseconds.
#[allow(dead_code)]
pub(crate) fn get_timestamp_bytes<T: TimeProvider + ?Sized>(time_provider: &T) -> u64 {
    time_provider
        .now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos() as u64
}

/// Build outputs for the transaction from the provided address and value and pairs.
#[allow(dead_code)]
fn build_outputs(output_data: &[OutputPair]) -> Vec<TxOut> {
    output_data
        .iter()
        .map(|pair| TxOut {
            value: pair.amount,
            script_pubkey: pair.address.script_pubkey(),
        })
        .collect()
}

#[allow(dead_code)]
/// Append a BIP141 witness commitment output if present.
fn append_default_witness_commitment(
    outputs: &mut Vec<TxOut>,
    default_witness_commitment: Option<&WitnessCommitment>,
) {
    if let Some(commitment) = default_witness_commitment {
        outputs.push(TxOut {
            value: Amount::ZERO,
            script_pubkey: commitment.to_script_buf(),
        });
    }
}

/// Build a coinbase transaction from the provided output pairs and height.
///
/// Example of a coinbase transaction:
/// coinbase generated by ckpool for regtest four txns
/// [2025-05-23 07:11:04.762] Coinb1: 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff2d02fa0100046803306804eba96d2d0c
/// [2025-05-23 07:11:04.762] Coinb2: 0a636b706f6f6c0a2f7032706f6f6c76322fffffffff034f2d822400000000
/// [2025-05-23 07:11:04.762] Header: 2000000065a7ea67c8083743a195e7ec5b424bdca660573756eab19968460fbf5e9a18370000000000000000000000000000000000000000000000000000000000000000683003
/// 68207fffff000000000000008000000000000000000000000000000000000000000000000000000000
///
/// Coinbase1:
/// 01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff - standard header for single output coinbase
/// 2d - script length
/// 02fa01 - height
/// 00 - empty flags
/// 04 68033068 - timestamp seconds
/// 04 eba96d2d - enonce1 from tv_nsec ??
/// 0c - 12, the length of the two nonces put together
#[allow(dead_code)]
/// Build a coinbase transaction for the share chain.
///
/// When `extranonce` is provided, it replaces the placeholder separator
/// in the scriptSig. When `None`, the separator placeholder is left in
/// place (used by the stratum server before split_coinbase).
pub(crate) fn build_bitcoin_coinbase_transaction(
    version: Version,
    output_data: &[OutputPair],
    height: i64,
    aux_flags: PushBytesBuf,
    default_witness_commitment: Option<&WitnessCommitment>,
    pool_signature: &[u8],
    commitment_hash: Option<sha256::Hash>,
    nsecs: u64,
    extranonce: Option<&[u8]>,
) -> Result<Transaction, WorkError> {
    if output_data.is_empty() {
        return Err(WorkError {
            message: "Empty output distribution".to_string(),
        });
    }

    let extranonce_bytes = match extranonce {
        Some(bytes) => bytes,
        None => &EXTRANONCE_SEPARATOR,
    };
    let mut extranonce_buf = PushBytesBuf::with_capacity(extranonce_bytes.len());
    extranonce_buf.extend_from_slice(extranonce_bytes).unwrap();

    let mut signature_buf = PushBytesBuf::with_capacity(pool_signature.len());
    signature_buf.extend_from_slice(pool_signature).unwrap();

    let coinbase_script_prefix = Builder::new()
        .push_int(height)
        .push_slice(aux_flags)
        .push_slice(extranonce_buf);

    let mut coinbase_builder = coinbase_script_prefix;
    if let Some(hash) = commitment_hash {
        coinbase_builder = coinbase_builder.push_slice(hash.as_byte_array());
    };
    let coinbase_script = coinbase_builder
        .push_slice(nsecs.to_le_bytes())
        .push_slice(signature_buf)
        .into_script();

    let mut outputs = build_outputs(output_data);
    append_default_witness_commitment(&mut outputs, default_witness_commitment);
    let lock_time = LockTime::from_height(height as u32 - 1).map_err(|_| WorkError {
        message: "Error getting locktime from height".into(),
    })?;

    let coinbase_tx = Transaction {
        version,
        lock_time,
        input: vec![TxIn {
            previous_output: bitcoin::OutPoint {
                txid: sha256d::Hash::all_zeros().into(),
                vout: u32::MAX,
            },
            script_sig: coinbase_script,
            sequence: BIP54_COINBASE_SEQUENCE,
            witness: Vec::<Vec<u8>>::new().into(),
        }],
        output: outputs,
    };
    Ok(coinbase_tx)
}

/// Splits the coinbase transaction into two parts: coinbase1 and coinbase2, separated by our
/// extranonce2 separator.
#[allow(dead_code)]
pub fn split_coinbase(coinbase: &Transaction) -> Result<(String, String), WorkError> {
    let deserialized_coinbase = serialize::<Transaction>(coinbase);
    let separator_pos = match deserialized_coinbase
        .as_slice()
        .windows(EXTRANONCE1_SIZE + EXTRANONCE2_SIZE)
        .position(|window| window == EXTRANONCE_SEPARATOR)
    {
        Some(pos) => pos,
        None => {
            return Err(WorkError {
                message: "Invalid coinbase transaction".to_string(),
            });
        }
    };

    let coinbase1 = hex::encode(&deserialized_coinbase[..separator_pos]);
    let coinbase2 = hex::encode(
        &deserialized_coinbase[separator_pos + (EXTRANONCE1_SIZE + EXTRANONCE2_SIZE)..],
    );
    Ok((coinbase1, coinbase2))
}

/// Parses the `coinbase2` hex string to extract the transaction outputs.
///
/// Based on `build_coinbase_transaction` and `split_coinbase`, `coinbase2`
/// has the following structure:
///
///  `commitment_hash` (optional: `[0x20] + [32 bytes]`)
///  `nsecs` (`[0x08] + [8 bytes]`)
///  `pool_signature` (`[len_byte] + [data]`)
///  `sequence` (4 bytes)
///  `output_count` (CompactSize)
///  `outputs` (serialized `Vec<TxOut>`)
///  `lock_time` (4 bytes)
///
/// This function parses this structure to return the `Vec<TxOut>`.
///
/// Detect whether a coinbase2 hex string starts with a commitment hash push.
///
/// Returns 33 (1 opcode byte + 32 data bytes) when the first byte is 0x20
/// (a 32-byte push), or 0 when the first byte is 0x08 (the nsecs 8-byte push).
/// This avoids relying on `share_commitment.is_some()`, which can be None in
/// solo mode even though the coinbase2 bytes still contain a commitment hash.
pub fn detect_commitment_hash_len_from_coinbase2(coinbase2_hex: &str) -> usize {
    // First byte in the hex is at positions 0..2
    if coinbase2_hex.len() >= 2 && &coinbase2_hex[0..2] == "20" {
        33
    } else {
        0
    }
}

/// coinbase2 layout: [commitment_hash?][nsecs][pool_sig][sequence][outputs][locktime]
/// The commitment_hash_len is 33 when present (1 opcode + 32 bytes), 0 when absent.
pub fn extract_outputs_from_coinbase2(
    coinbase2_hex: &str,
    commitment_hash_len: usize,
    pool_signature_len: usize,
) -> Result<Vec<TxOut>, WorkError> {
    let coinbase2_bytes = Vec::from_hex(coinbase2_hex).map_err(|_| WorkError {
        message: "Error parsing coinbase hex".into(),
    })?;

    let nsecs_push_len = 1 + 8; // opcode + 8 bytes for u64
    let pool_sig_push_len = 1 + pool_signature_len;
    let script_sig_part2_len = commitment_hash_len + nsecs_push_len + pool_sig_push_len;
    let output_data_start_index = script_sig_part2_len + SEQUENCE_LENGTH;

    // Bounds check: need at least start_index + LOCKTIME_LENGTH bytes
    let min_len = output_data_start_index + LOCKTIME_LENGTH;
    if coinbase2_bytes.len() < min_len {
        return Err(WorkError {
            message: "coinbase2 too short".into(),
        });
    }

    let output_data_end_index = coinbase2_bytes.len() - LOCKTIME_LENGTH;
    let output_data = &coinbase2_bytes[output_data_start_index..output_data_end_index];

    deserialize::<Vec<TxOut>>(output_data).map_err(|_| WorkError {
        message: "Bad outputs in coinbase2".into(),
    })
}

/// Extract the commitment hash from a bitcoin coinbase transaction's scriptSig.
///
/// The coinbase scriptSig layout is: push(height), push(commitment_hash_32bytes), ...
/// Extract the block height from the coinbase scriptSig (BIP34).
///
/// The first instruction in the coinbase scriptSig is the block height
/// encoded via `push_int`. For heights > 16 this produces a
/// `PushBytes` instruction decoded with `read_scriptint`. For heights
/// 0-16 the builder emits a single opcode (OP_0 or OP_1..OP_16).
///
/// Returns an error if the decoded height is negative.
pub fn extract_height_from_coinbase(coinbase: &Transaction) -> Result<u64, WorkError> {
    let input = coinbase.input.first().ok_or_else(|| WorkError {
        message: "Bitcoin coinbase has no inputs".to_string(),
    })?;

    let mut instructions = input.script_sig.instructions();

    let height_instruction = instructions
        .next()
        .ok_or_else(|| WorkError {
            message: "Bitcoin coinbase scriptSig is empty".to_string(),
        })?
        .map_err(|error| WorkError {
            message: format!("Invalid bitcoin coinbase scriptSig: {error}"),
        })?;

    match height_instruction {
        Instruction::PushBytes(bytes) => {
            let raw = bytes.as_bytes();
            let height = bitcoin::script::read_scriptint(raw).map_err(|error| WorkError {
                message: format!("Invalid block height scriptint: {error}"),
            })?;
            if height < 0 {
                return Err(WorkError {
                    message: format!("Block height must not be negative: {height}"),
                });
            }
            Ok(height as u64)
        }
        Instruction::Op(opcode) => {
            let byte = opcode.to_u8();
            if byte == opcodes::OP_0.to_u8() {
                Ok(0)
            } else if byte >= opcodes::all::OP_PUSHNUM_1.to_u8()
                && byte <= opcodes::all::OP_PUSHNUM_16.to_u8()
            {
                Ok(u64::from(byte - opcodes::all::OP_PUSHNUM_1.to_u8() + 1))
            } else {
                Err(WorkError {
                    message: format!("Unexpected opcode in block height position: {opcode}"),
                })
            }
        }
    }
}

/// Extracts the commitment hash from the coinbase scriptSig.
///
/// Skips the first three instructions (height, aux_flags, EXTRANONCE_SEPARATOR)
/// and reads the fourth instruction, which should be a 32-byte push containing
/// the commitment hash.
pub fn extract_commitment_hash_from_coinbase(
    coinbase: &Transaction,
) -> Result<sha256::Hash, WorkError> {
    let input = coinbase.input.first().ok_or_else(|| WorkError {
        message: "Bitcoin coinbase has no inputs".to_string(),
    })?;

    let mut instructions = input.script_sig.instructions();

    // Script layout: [height][aux_flags][EXTRANONCE_SEPARATOR][commitment_hash][nsecs][pool_sig]
    // Skip height, aux_flags, and EXTRANONCE_SEPARATOR (first 3 instructions)
    for _ in 0..3 {
        instructions
            .next()
            .ok_or_else(|| WorkError {
                message: "Bitcoin coinbase scriptSig too short".to_string(),
            })?
            .map_err(|error| WorkError {
                message: format!("Invalid bitcoin coinbase scriptSig: {error}"),
            })?;
    }

    // Fourth instruction should be the 32-byte commitment hash
    let commitment_instruction = instructions
        .next()
        .ok_or_else(|| WorkError {
            message: "Bitcoin coinbase scriptSig missing commitment hash".to_string(),
        })?
        .map_err(|error| WorkError {
            message: format!("Invalid bitcoin coinbase scriptSig: {error}"),
        })?;

    match commitment_instruction {
        Instruction::PushBytes(bytes) if bytes.len() == 32 => {
            let mut hash_bytes = [0u8; 32];
            hash_bytes.copy_from_slice(bytes.as_bytes());
            Ok(sha256::Hash::from_byte_array(hash_bytes))
        }
        _ => Err(WorkError {
            message: "Bitcoin coinbase scriptSig does not contain a 32-byte commitment hash"
                .to_string(),
        }),
    }
}

#[cfg(test)]
mod tests {
    use crate::shares::share_commitment::ShareCommitment;
    use crate::shares::witness_commitment::WitnessCommitment;
    use crate::utils::time_provider::SystemTimeProvider;
    use bitcoin::hex::DisplayHex;
    use std::str::FromStr;

    use super::*;
    use crate::{
        stratum::work::block_template::BlockTemplate,
        test_utils::{create_test_commitment, genesis_for_tests},
    };

    #[test]
    fn test_parse_address_valid_mainnet() {
        let addr = "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A";
        let result = parse_address(addr, Network::Bitcoin);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_address_valid_testnet() {
        let addr = "tb1q0afww6y0kgl4tyjjyv6xlttvfwdfqxvrfzz35f";
        let result = parse_address(addr, Network::Testnet);
        assert!(result.is_ok());
    }

    #[test]
    fn test_parse_address_invalid_format() {
        let addr = "not_a_valid_address";
        let result = parse_address(addr, Network::Bitcoin);
        assert!(result.is_err());
        assert!(
            result
                .err()
                .unwrap()
                .to_string()
                .contains("Invalid address")
        );
    }

    #[test]
    fn test_parse_address_wrong_network() {
        // This is a mainnet address, but we require testnet
        let addr = "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A";
        let result = parse_address(addr, Network::Testnet);
        assert!(result.is_err());
        let msg = result.err().unwrap().to_string();
        assert!(msg.contains("Address does not match network"));
        assert!(msg.contains("testnet"));
    }

    #[test]
    fn test_build_coinbase_transaction_without_default_witness() {
        let addr = parse_address(
            "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A",
            bitcoin::Network::Bitcoin,
        )
        .unwrap();
        let value = Amount::from_str("50 BTC").unwrap();
        let height = 100;
        let coinbase = build_bitcoin_coinbase_transaction(
            Version(2),
            &[OutputPair {
                address: addr.clone(),
                amount: value,
            }],
            height,
            PushBytesBuf::from(&[0u8]),
            None,
            &[],
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        // Check version and BIP54 lock_time (height - 1)
        assert_eq!(coinbase.version, Version(2));
        assert_eq!(
            coinbase.lock_time,
            LockTime::from_height(height as u32 - 1).unwrap()
        );

        // Check input
        assert_eq!(coinbase.input.len(), 1);
        let input = &coinbase.input[0];
        assert_eq!(
            input.previous_output.txid,
            sha256d::Hash::all_zeros().into()
        );
        assert_eq!(input.previous_output.vout, u32::MAX);
        assert_eq!(input.sequence, BIP54_COINBASE_SEQUENCE);

        let script_bytes = input.script_sig.as_bytes();
        // Check coinbase script contains height
        assert!(script_bytes.contains(&(height as u8)));
        // Check coinbase script contains extranonce separator
        assert!(
            script_bytes
                .windows(EXTRANONCE1_SIZE + EXTRANONCE2_SIZE)
                .any(|w| w == EXTRANONCE_SEPARATOR)
        );

        // Check output
        assert_eq!(coinbase.output.len(), 1);
        let output = &coinbase.output[0];
        assert_eq!(output.value, value);
        assert_eq!(output.script_pubkey, addr.script_pubkey());
    }

    #[test]
    fn test_split_coinbase_without_default_commitment() {
        let addr = parse_address(
            "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A",
            bitcoin::Network::Bitcoin,
        )
        .unwrap();
        let value = Amount::from_str("50 BTC").unwrap();
        let height = 100;
        let coinbase = build_bitcoin_coinbase_transaction(
            Version(2),
            &[OutputPair {
                address: addr.clone(),
                amount: value,
            }],
            height,
            PushBytesBuf::from(&[0u8]),
            None,
            &[],
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let (coinbase1, coinbase2) = split_coinbase(&coinbase).unwrap();

        // Reconstruct the coinbase by concatenating coinbase1, extranonce2, and coinbase2
        let extranonce2 = EXTRANONCE_SEPARATOR.to_vec();
        let coinbase1_bytes = hex::decode(&coinbase1).unwrap();
        let coinbase2_bytes = hex::decode(&coinbase2).unwrap();

        let mut reconstructed = Vec::new();
        reconstructed.extend_from_slice(&coinbase1_bytes);
        reconstructed.extend_from_slice(&extranonce2);
        reconstructed.extend_from_slice(&coinbase2_bytes);

        let reconstructed_coinbase: Transaction =
            bitcoin::consensus::deserialize(&reconstructed).unwrap();
        assert_eq!(reconstructed_coinbase, coinbase);
    }

    #[test]
    fn test_building_coinbase_with_regtest_ckpool_data() {
        // Load GBT and expected notify JSON
        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/gbt.json"
        );
        let template: BlockTemplate = serde_json::from_str(&data).expect("Invalid JSON");

        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/notify.json"
        );
        let _notify: serde_json::Value = serde_json::from_str(&data).expect("Invalid JSON");

        // Address used in ckpool regtest conf
        let address = parse_address(
            "bcrt1qe2qaq0e8qlp425pxytrakala7725dynwhknufr",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let donation_address = parse_address(
            "bcrt1qlk935ze2fsu86zjp395uvtegztrkaezawxx0wf",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let coinbase = build_bitcoin_coinbase_transaction(
            Version(1), // ckpool uses version 1
            &[
                OutputPair {
                    address: address.clone(),
                    amount: Amount::from_str("49 BTC").unwrap(),
                },
                OutputPair {
                    address: donation_address.clone(),
                    amount: Amount::from_str("1 BTC").unwrap(), // ckpool uses 2% donation address. We replicate that for test.
                },
            ],
            template.height as i64,
            PushBytesBuf::from(&[0u8]),
            template
                .default_witness_commitment
                .as_deref()
                .and_then(|hex_str| WitnessCommitment::from_hex(hex_str).ok())
                .as_ref(),
            b"P2Poolv2",
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        assert_eq!(coinbase.version, Version(1));
        assert_eq!(
            coinbase.lock_time,
            LockTime::from_height(template.height as u32 - 1).unwrap()
        );
        assert_eq!(coinbase.input.len(), 1);
        let input = &coinbase.input[0];
        assert_eq!(
            input.previous_output.txid,
            sha256d::Hash::all_zeros().into()
        );
        assert_eq!(input.previous_output.vout, u32::MAX);
        assert_eq!(input.sequence, BIP54_COINBASE_SEQUENCE);
        assert_eq!(input.witness.len(), 0); // No witness data in this test
        assert_eq!(coinbase.output.len(), 3);
        let output1 = &coinbase.output[0];
        let output2 = &coinbase.output[1];
        let output3 = &coinbase.output[2];

        assert_eq!(output1.value, Amount::from_str("49 BTC").unwrap());
        assert_eq!(output1.script_pubkey, address.script_pubkey());

        assert_eq!(output2.value, Amount::from_str("1 BTC").unwrap());
        assert_eq!(output2.script_pubkey, donation_address.script_pubkey());

        assert_eq!(output3.value, Amount::ZERO);
        assert_eq!(
            Some(output3.script_pubkey.to_hex_string()),
            template.default_witness_commitment
        );

        // Check the coinbase input script layout:
        // [height][flags][EXTRANONCE_SEPARATOR][nsecs][pool_sig]
        assert_eq!(coinbase.input[0].script_sig.len(), 36);
        let script_bytes = coinbase.input[0].script_sig.as_bytes();
        assert_eq!(script_bytes[0], 2);
        assert_eq!(script_bytes[1..3].as_hex().to_string(), "fa01"); // Height 506 in little-endian
        assert_eq!(script_bytes[3..5].as_hex().to_string(), "0100"); // Flags (empty in this case)
        assert_eq!(script_bytes[5..6].as_hex().to_string(), "0c"); // Extranonce separator length (12 bytes)
        assert_eq!(script_bytes[6..18], EXTRANONCE_SEPARATOR); // Extranonce separator
        assert_eq!(script_bytes[18..19].as_hex().to_string(), "08"); // Timestamp length (8 bytes for u64 nanos)
        assert_eq!(script_bytes[27], 8u8); // Pool signature length
        assert_eq!(
            &script_bytes[28..36],
            b"P2Poolv2", // Check the pool signature
        );
    }

    #[test]
    fn test_building_coinbase_with_share_commitment_should_include_the_commitment() {
        // Load GBT and expected notify JSON
        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/gbt.json"
        );
        let template: BlockTemplate = serde_json::from_str(&data).expect("Invalid JSON");

        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/notify.json"
        );
        let _notify: serde_json::Value = serde_json::from_str(&data).expect("Invalid JSON");

        // Address used in ckpool regtest conf
        let address = parse_address(
            "bcrt1qe2qaq0e8qlp425pxytrakala7725dynwhknufr",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let donation_address = parse_address(
            "bcrt1qlk935ze2fsu86zjp395uvtegztrkaezawxx0wf",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let genesis = genesis_for_tests();

        let share_commitment = create_test_commitment();
        let share_commitment = ShareCommitment {
            prev_share_blockhash: genesis.block_hash(),
            ..share_commitment
        };

        let share_commitment_cloned = share_commitment.clone();

        let coinbase = build_bitcoin_coinbase_transaction(
            Version(1), // ckpool uses version 1
            &[
                OutputPair {
                    address: address.clone(),
                    amount: Amount::from_str("49 BTC").unwrap(),
                },
                OutputPair {
                    address: donation_address.clone(),
                    amount: Amount::from_str("1 BTC").unwrap(), // ckpool uses 2% donation address. We replicate that for test.
                },
            ],
            template.height as i64,
            PushBytesBuf::from(&[0u8]),
            template
                .default_witness_commitment
                .as_deref()
                .and_then(|hex_str| WitnessCommitment::from_hex(hex_str).ok())
                .as_ref(),
            b"P2Poolv2",
            Some(share_commitment.hash()),
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        assert_eq!(coinbase.version, Version(1));
        assert_eq!(
            coinbase.lock_time,
            LockTime::from_height(template.height as u32 - 1).unwrap()
        );
        assert_eq!(coinbase.input.len(), 1);
        let input = &coinbase.input[0];
        assert_eq!(
            input.previous_output.txid,
            sha256d::Hash::all_zeros().into()
        );
        assert_eq!(input.previous_output.vout, u32::MAX);
        assert_eq!(input.sequence, BIP54_COINBASE_SEQUENCE);
        assert_eq!(input.witness.len(), 0); // No witness data in this test
        assert_eq!(coinbase.output.len(), 3);
        let output1 = &coinbase.output[0];
        let output2 = &coinbase.output[1];
        let output3 = &coinbase.output[2];

        assert_eq!(output1.value, Amount::from_str("49 BTC").unwrap());
        assert_eq!(output1.script_pubkey, address.script_pubkey());

        assert_eq!(output2.value, Amount::from_str("1 BTC").unwrap());
        assert_eq!(output2.script_pubkey, donation_address.script_pubkey());

        assert_eq!(output3.value, Amount::ZERO);
        assert_eq!(
            Some(output3.script_pubkey.to_hex_string()),
            template.default_witness_commitment
        );

        // Check the coinbase input script layout:
        // [height][flags][EXTRANONCE_SEPARATOR][commitment_hash][nsecs][pool_sig]
        assert_eq!(coinbase.input[0].script_sig.len(), 69);
        let script_bytes = coinbase.input[0].script_sig.as_bytes();
        assert_eq!(script_bytes[0], 2);
        assert_eq!(script_bytes[1..3].as_hex().to_string(), "fa01"); // Height 506 in little-endian
        assert_eq!(script_bytes[3..5].as_hex().to_string(), "0100"); // Flags (empty in this case)
        assert_eq!(script_bytes[5..6].as_hex().to_string(), "0c"); // Extranonce separator length (12 bytes)
        assert_eq!(script_bytes[6..18], EXTRANONCE_SEPARATOR); // Extranonce separator
        assert_eq!(script_bytes[18..19].as_hex().to_string(), "20"); // Commitment hash length (32 bytes)
        assert_eq!(
            script_bytes[19..51].as_hex().to_string(),
            share_commitment_cloned
                .hash()
                .as_byte_array()
                .to_lower_hex_string()
        ); // Share commitment hash
        assert_eq!(script_bytes[51..52].as_hex().to_string(), "08"); // Timestamp length (8 bytes for u64 nanos)
        assert_eq!(script_bytes[60], 8u8); // Pool signature length
        assert_eq!(
            &script_bytes[61..69],
            b"P2Poolv2", // Check the pool signature
        );
    }

    #[test]
    fn test_extract_outputs_from_coinbase2_integration() {
        // This Test builds splits then parse

        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/gbt.json"
        );
        let template: BlockTemplate = serde_json::from_str(data).expect("Invalid JSON");

        let address = parse_address(
            "bcrt1qe2qaq0e8qlp425pxytrakala7725dynwhknufr",
            bitcoin::Network::Regtest,
        )
        .unwrap();
        let donation_address = parse_address(
            "bcrt1qlk935ze2fsu86zjp395uvtegztrkaezawxx0wf",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let output_pairs = vec![
            OutputPair {
                address: address.clone(),
                amount: Amount::from_str("49 BTC").unwrap(),
            },
            OutputPair {
                address: donation_address.clone(),
                amount: Amount::from_str("1 BTC").unwrap(),
            },
        ];

        let pool_sig = b"P2Poolv2";
        //  Build and Split
        let coinbase_tx = build_bitcoin_coinbase_transaction(
            Version(1),
            &output_pairs,
            template.height as i64,
            PushBytesBuf::from(&[0u8]),
            template
                .default_witness_commitment
                .as_deref()
                .and_then(|hex_str| WitnessCommitment::from_hex(hex_str).ok())
                .as_ref(),
            pool_sig,
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let expected_outputs = coinbase_tx.output.clone();
        assert_eq!(expected_outputs.len(), 3); // 2 payments + 1 witness

        let (_coinbase1, coinbase2_hex) = split_coinbase(&coinbase_tx).unwrap();

        //  Parse
        let extracted_outputs =
            extract_outputs_from_coinbase2(&coinbase2_hex, 0, pool_sig.len()).unwrap();

        //  Verify
        assert_eq!(extracted_outputs, expected_outputs);
        assert_eq!(
            extracted_outputs[0].value,
            Amount::from_str("49 BTC").unwrap()
        );
        assert_eq!(
            extracted_outputs[1].value,
            Amount::from_str("1 BTC").unwrap()
        );
        assert_eq!(extracted_outputs[2].value, Amount::ZERO); // Witness
    }

    #[test]
    fn test_extract_outputs_from_coinbase2_bounds_checking() {
        // Test empty input
        let result = extract_outputs_from_coinbase2("", 0, 8);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("too short"));

        // Test input that's too short for the expected structure
        // With commitment_hash_len=0, pool_signature_len=8:
        // min_len = 0 + 17(nsecs) + 9(pool_sig) + 4(seq) + 4(locktime) = 34 bytes = 68 hex chars
        let short_hex = "00112233445566778899aabbccddeeff"; // 16 bytes = 32 hex chars
        let result = extract_outputs_from_coinbase2(short_hex, 0, 8);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("too short"));

        // Test exactly at minimum length (should fail on deserialize, not bounds)
        // Need 34 bytes minimum: 68 hex chars
        let min_hex = hex::encode([0u8; 34]);
        let result = extract_outputs_from_coinbase2(&min_hex, 0, 8);
        assert!(result.is_err());
        // This should fail on deserialize, not bounds check
        assert!(result.unwrap_err().message.contains("Bad outputs"));

        // Test invalid hex
        let result = extract_outputs_from_coinbase2("not_valid_hex!", 0, 8);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("parsing coinbase hex"));
    }

    #[test]
    fn test_extract_commitment_hash_from_coinbase_with_commitment() {
        let data = include_str!(
            "../../../../p2poolv2_tests/test_data/gbt/regtest/ckpool/four-txns/gbt.json"
        );
        let template: BlockTemplate = serde_json::from_str(data).expect("Invalid JSON");

        let address = parse_address(
            "bcrt1qe2qaq0e8qlp425pxytrakala7725dynwhknufr",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let share_commitment = ShareCommitment {
            prev_share_blockhash: genesis_for_tests().block_hash(),
            ..create_test_commitment()
        };
        let expected_hash = share_commitment.hash();

        let coinbase = build_bitcoin_coinbase_transaction(
            Version(1),
            &[OutputPair {
                address: address.clone(),
                amount: Amount::from_str("50 BTC").unwrap(),
            }],
            template.height as i64,
            PushBytesBuf::from(&[0u8]),
            None,
            b"P2Poolv2",
            Some(expected_hash),
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let extracted_hash = extract_commitment_hash_from_coinbase(&coinbase).unwrap();
        assert_eq!(extracted_hash, expected_hash);
    }

    #[test]
    fn test_extract_commitment_hash_from_coinbase_without_commitment() {
        let address = parse_address(
            "bcrt1qe2qaq0e8qlp425pxytrakala7725dynwhknufr",
            bitcoin::Network::Regtest,
        )
        .unwrap();

        let coinbase = build_bitcoin_coinbase_transaction(
            Version(1),
            &[OutputPair {
                address: address.clone(),
                amount: Amount::from_str("50 BTC").unwrap(),
            }],
            100,
            PushBytesBuf::from(&[0u8]),
            None,
            b"P2Poolv2",
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let result = extract_commitment_hash_from_coinbase(&coinbase);
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .message
                .contains("does not contain a 32-byte commitment hash")
        );
    }

    #[test]
    fn test_extract_commitment_hash_from_coinbase_empty_inputs() {
        let coinbase = Transaction {
            version: Version(1),
            lock_time: LockTime::ZERO,
            input: vec![],
            output: vec![],
        };

        let result = extract_commitment_hash_from_coinbase(&coinbase);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("no inputs"));
    }

    #[test]
    fn test_extract_height_from_coinbase() {
        let addr = parse_address(
            "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A",
            bitcoin::Network::Bitcoin,
        )
        .unwrap();
        let height = 506;
        let coinbase = build_bitcoin_coinbase_transaction(
            Version(2),
            &[OutputPair {
                address: addr,
                amount: Amount::from_str("50 BTC").unwrap(),
            }],
            height,
            PushBytesBuf::from(&[0u8]),
            None,
            &[],
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let extracted_height = extract_height_from_coinbase(&coinbase).unwrap();
        assert_eq!(extracted_height, height as u64);
    }

    #[test]
    fn test_extract_height_from_coinbase_large_height() {
        let addr = parse_address(
            "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A",
            bitcoin::Network::Bitcoin,
        )
        .unwrap();
        let height = 840_000;
        let coinbase = build_bitcoin_coinbase_transaction(
            Version(2),
            &[OutputPair {
                address: addr,
                amount: Amount::from_str("3.125 BTC").unwrap(),
            }],
            height,
            PushBytesBuf::from(&[0u8]),
            None,
            &[],
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let extracted_height = extract_height_from_coinbase(&coinbase).unwrap();
        assert_eq!(extracted_height, height as u64);
    }

    #[test]
    fn test_extract_height_from_coinbase_sub_16_height() {
        let addr = parse_address(
            "1HpRF3JgafxaqjhMEjLNbevpRVvAp15t3A",
            bitcoin::Network::Bitcoin,
        )
        .unwrap();
        let height = 10;
        let coinbase = build_bitcoin_coinbase_transaction(
            Version(2),
            &[OutputPair {
                address: addr,
                amount: Amount::from_str("3.125 BTC").unwrap(),
            }],
            height,
            PushBytesBuf::from(&[0u8]),
            None,
            &[],
            None,
            get_timestamp_bytes(&SystemTimeProvider),
            None,
        )
        .unwrap();

        let extracted_height = extract_height_from_coinbase(&coinbase).unwrap();
        assert_eq!(extracted_height, height as u64);
    }

    #[test]
    fn test_extract_height_from_coinbase_no_inputs() {
        let coinbase = Transaction {
            version: Version(2),
            lock_time: LockTime::ZERO,
            input: vec![],
            output: vec![],
        };

        let result = extract_height_from_coinbase(&coinbase);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("no inputs"));
    }

    #[test]
    fn test_extract_height_from_coinbase_negative_height() {
        let script_sig = Builder::new().push_int(-100).into_script();
        let coinbase = Transaction {
            version: Version(2),
            lock_time: LockTime::ZERO,
            input: vec![TxIn {
                previous_output: bitcoin::OutPoint {
                    txid: bitcoin::hashes::sha256d::Hash::all_zeros().into(),
                    vout: u32::MAX,
                },
                script_sig,
                sequence: Sequence::MAX,
                witness: Vec::<Vec<u8>>::new().into(),
            }],
            output: vec![],
        };

        let result = extract_height_from_coinbase(&coinbase);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("must not be negative"));
    }
}
