name: p2poolv2

services:
  bitcoind:
    build:
      context: bitcoind
    volumes:
      - bitcoin_data:/data
    ports:
      - "${BTC_P2P_PORT:-38333}:${BTC_P2P_PORT:-38333}" # P2P port
      - "${BTC_RPC_PORT:-38332}:${BTC_RPC_PORT:-38332}" # RPC port
      - "28332:28332" # ZMQ port is always the same
    environment:
      - NETWORK=${NETWORK:-signet}
    command: -conf=/etc/bitcoin/bitcoin-${NETWORK:-signet}.conf -datadir=/data
    restart: unless-stopped
    networks:
      - p2poolv2_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  bitcoin-bootstrap:
    build:
      context: bitcoind
    depends_on:
      bitcoind:
        condition: service_started
    entrypoint: ["/usr/local/bin/bootstrap.sh"]
    environment:
      - NETWORK=${NETWORK:-signet}
      - TARGET_HEIGHT=32
    healthcheck:
      disable: true
    restart: "no"
    networks:
      - p2poolv2_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  p2poolv2:
    extends:
      file: docker-compose.p2poolv2.yml
      service: p2poolv2
    depends_on:
      bitcoind:
        condition: service_healthy
    networks:
      - p2poolv2_network

  mujina_minerd:
    extends:
      file: docker-compose.p2poolv2.yml
      service: mujina_minerd
    networks:
      - p2poolv2_network

volumes:
  bitcoin_data:
  p2poolv2_data:

networks:
  p2poolv2_network:
    driver: bridge
