[package]
name = "bitcoindrpc"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[lib]
path = "src/lib.rs"

[dependencies]
base64.workspace = true
bitcoin.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
serde_json.workspace = true
mockall = { version = "0.13.1", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }
wiremock = "0.6.2"
mockall = "0.13.1"

[features]
mock = ["mockall"]